### ISSUE TITLE
Query should not be limited by procedures

### ISSUE THREAD

**Issue by mcjustin** [uwcirg/dawg-to-fhir#1]
Per https://github.com/uwcirg/dawg-to-fhir/blob/main/paintracker_daily_update_dawg_to_fhir_via_fume.py#L32 "CPR patients who have/had a scheduled visit in -2 to +7 days and also ever had one of the procedures of interest":

The query should not be limited by procedures - the system should PUT FHIR Patient for all DAWG patients who have CPR appts in the time window, regardless of what procedures the DAWG shows for them.

**Comment by jsibley** [comment]
Fixed in [last commit](https://github.com/uwcirg/dawg-to-fhir/commit/7a784de3dcd171867c55c7b2d4b27de09cd07ebf).
